// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

// Generated by build/Update-CommandReference.ps1 (Alt3.Docusaurus.Powershell).
import commands from "./docs/commands/docusaurus.sidebar.js";

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docsSidebar: [
    "intro",
    {
      type: "category",
      label: "Getting started",
      collapsed: false,
      items: [
        "getting-started/installation",
        "getting-started/authentication",
        "getting-started/permissions",
      ],
    },
  ],
  commandsSidebar: [
    {
      type: "category",
      label: "Cmdlet reference",
      collapsed: false,
      link: { type: "doc", id: "commands/index" },
      items: commands,
    },
  ],
};

export default sidebars;
