name: Generate Resources & Deploy GitHub Pages
on:
  push:
    branches:
        - main
jobs:

    documentation:
      runs-on: ubuntu-latest
      name: 'Create markdown documentation'

      steps:
        - name: Install latest PSCloudPC module
          shell: pwsh
          run: |
            Set-PSRepository PSGallery -InstallationPolicy Trusted
            Install-Module PSCloudPC -ErrorAction Stop
    
        - name: Install PSPlaty module
          shell: pwsh
          run: |
            Install-Module PlatyPS -ErrorAction Stop      

    deploy:
        needs: documentation
        runs-on: ubuntu-latest

    
        steps:
          - uses: actions/checkout@v3
          - uses: actions/setup-python@v4
            with:
              python-version: 3.x
          - run: |
              pip install mkdocs-material mkdocs-material-extensions
              pip install mkdocs-include-dir-to-nav
              pip install pillow cairosvg
          - name: Deploy
            working-directory: .
            run: mkdocs gh-deploy --force
