name: regenerateDocs

on:
  schedule:
    - cron: "0 6 * * *"

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Check out PSCloudPC-site code
        uses: actions/checkout@v2
        with:
          repository: Windows365Management/PSCloudPC-site
          ref: main
          path: PSCloudPC-site
      - name: Check out PSCloudPC code
        uses: actions/checkout@v2
        with:
          repository: Windows365Management/PSCloudPC
          ref: develop
          path: PSCloudPC
      - name: Install platyPS module
        shell: pwsh
        run: |
          Install-Module -Name platyPS -Force
          ls
      - name: Regenerate Docs
        shell: pwsh
        run: |
          Import-Module platyPS -Force
          Import-Module ./PSCloudPC/Src/PSCloudPC.psm1 -Force
          New-MarkdownHelp -Module "PSCloudPC" -OutputFolder "./PSCloudPC-site/docs" -Force
      - name: Commit files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Regenerated Docs"
          branch: main